#!/data/data/com.termux/files/usr/bin/bash

### install dependencies 
pkg install root-repo x11-repo axel bsdtar proot xz-utils neofetch pulseaudio -y

### Ascii
neofetch --ascii_distro Ubuntu -L

### Download Tarball
axel -a --search -o ubuntu-arm64.tar.xz https://github.com/termux/proot-distro/releases/download/v4.11.0/ubuntu-jammy-arm-pd-v4.11.0.tar.xz

### Decompressed tarball
echo "Decompressing Rootfs...!!!"
proot --link2symlink bsdtar -xpJf ubuntu-arm64.tar.xz 2>/dev/null

### Make executable bin
wget -O $PREFIX/bin/ubuntu https://raw.githubusercontent.com/xiv3r/Ubuntu-Termux/refs/heads/main/bin/ubuntu

### Fix shebang
termux-fix-shebang $PREFIX/bin/ubuntu 
chmod 700 $PREFIX/bin/ubuntu 
ubuntu 
